### PR TITLE
arm: add -fsigned-char to avoid differences between x86 and arm

### PR DESCRIPTION
**Pull request by q4a**
I'm not sure about ARM MacOS, but in ARM Linux we have default char == unsigned char, while on x86_64 Linux we have default char == signed char.
This leads to crash on ARM Linux, because there is:
1) `cur_player_add=-1; ` - on ARM Linux will lead to `cur_player_add==255`
2) check `cur_player_add<0` will always false.
https://github.com/KD-lab-Open-Source/Perimeter/blob/f58b3ae7369df502a1e3dcd697b9791a4b1a14c5/Source/Render/D3D/D3DRenderTilemap.cpp#L1488-L1494
Screenshot from 2023-02-10 16-12-24
Screenshot from 2023-02-10 16-13-59

### CODE REVIEW

**Comment by proydakov** [comment]
Should we try to use int instead of char in this context? Or are there other places with a similar error?

**Comment by q4a** [comment]
> Should we try to use int instead of char in this context?

I don't know. I just want to fix error that I got on ARM Linux

> Or are there other places with a similar error?

I don't think so.

**Comment by proydakov** [comment]
Changing the global compiler flags is a really complex change for all project subsystems.
I prefer int8_t in this place. It's much safer.

**Comment by IonAgorria** [comment]
While I agree that changing global compiler flags is tricky, the game was made on a platform where the assumption was that chars were signed so might be good to keep that way on other platforms by default just in case.

On the other side I also prefer if we replaced all basic types with explicit data types over time, will probably change this when I have to refactor the renderer.

There is any reason why SDL2 dependencies where changed in CMake? what distro you are compiling this on ARM to require these changes?

Also I think it would be better if the flag was added inside this section since the one changing is dedicated to floating point math / FPU setup
https://github.com/KD-lab-Open-Source/Perimeter/blob/cmake/CMakeLists.txt#L191

**Comment by IonAgorria** [comment]
Closing since the changes were merged already, thanks!

**Pull request closed without merging**
